config/routes.rb
Sandwiches::Application.routes.draw do
  resources :sandwiches

  root to: "sandwiches#index"  

end

app/models/sandwich.rb
class Sandwich
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  # GET /sandwiches
  # GET /sandwiches.json
  def index
    @sandwiches = Sandwich.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sandwiches }
    end
  end

  # GET /sandwiches/1
  # GET /sandwiches/1.json
  def show
    @sandwich = Sandwich.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sandwich }
    end
  end

  # GET /sandwiches/new
  # GET /sandwiches/new.json
  def new
    @sandwich = Sandwich.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sandwich }
    end
  end

  # GET /sandwiches/1/edit
  def edit
    @sandwich = Sandwich.find(params[:id])
  end

  # POST /sandwiches
  # POST /sandwiches.json
  def create
    @sandwich = Sandwich.new(params[:sandwich])

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully created.' }
        format.json { render json: @sandwich, status: :created, location: @sandwich }
      else
        format.html { render action: "new" }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sandwiches/1
  # PUT /sandwiches/1.json
  def update
    @sandwich = Sandwich.find(params[:id])

    respond_to do |format|
      if @sandwich.update_attributes(params[:sandwich])
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sandwiches/1
  # DELETE /sandwiches/1.json
  def destroy
    @sandwich = Sandwich.find(params[:id])
    @sandwich.destroy

    respond_to do |format|
      format.html { redirect_to sandwiches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandwiches</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sandwiches/_form.html.erb
<%= form_for(@sandwich) do |f| %>
  <% if @sandwich.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sandwich.errors.count, "error") %> prohibited this sandwich from being saved:</h2>

      <ul>
      <% @sandwich.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sandwiches/edit.html.erb
<h1>Editing sandwich</h1>

<%= render 'form' %>

<%= link_to 'Show', @sandwich %> |
<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/index.html.erb
<h1>Listing sandwiches</h1>
<%= paginate @sandwiches %>
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sandwiches.each do |sandwich| %>
  <tr>
    <td><%= sandwich.name %></td>
    <td><%= sandwich.description %></td>
    <td><%= link_to 'Show', sandwich %></td>
    <td><%= link_to 'Edit', edit_sandwich_path(sandwich) %></td>
    <td><%= link_to 'Destroy', sandwich, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sandwich', new_sandwich_path %>

app/views/sandwiches/new.html.erb
<h1>New sandwich</h1>

<%= render 'form' %>

<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sandwich.name %>
</p>

<p>
  <b>Description:</b>
  <%= @sandwich.description %>
</p>


<%= link_to 'Edit', edit_sandwich_path(@sandwich) %> |
<%= link_to 'Back', sandwiches_path %>